In [5]:
# Write a Python program to print the NumPy version in your system.

import numpy as np
print(np.__version__)
    

1.19.2


In [2]:
# Write a Python program to reverse an array(first element becomes last).

x=np.array([1,2,3,4,5])
x[::-1]


array([5, 4, 3, 2, 1])

In [7]:
# Write a Python program to convert a list and tuple into arrays.

tpl=([1,2,3,4,5],[8,9,4,5,6])
lst=[6,7,8,9,1]
print(np.asarray(tpl))
print(np.array(lst))

[[1 2 3 4 5]
 [8 9 4 5 6]]
[6 7 8 9 1]


In [15]:
# Write a Python program to find common values between two arrays.

arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,1])
print(np.intersect1d(arr1,arr2))


[1 4 5]


In [21]:
# Write a Python program compare two arrays using numpy.

arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,1])
print(arr1>=arr2)


[False False False False  True]
[False False False False  True]


In [29]:
# Write a Python program to change the dimension of an array.

arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array(arr1).reshape(5,2))
# or
print()
arr1.shape=(2,5)
print(arr1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

arr1=np.arange(100)
arr2=arr1[(arr1%3==0) | (arr1%5==0)]
print(arr2)
print(np.sum(arr1[(arr1%3==0) | (arr1%5==0)]))


[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [36]:
# Write a Python program to convert a NumPy array into Python list structure.

arr1=np.arange(20).reshape(4,5)
print(arr1)
print('\n',arr1.tolist())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]


In [22]:
# Write a Python program to how to add an extra column to a numpy array.

arr1=np.array([[1,2,3],[2,6,7]])
arr2=np.array([[9],[4]])           # As two rows present in first array so give here 2row element 
print(np.append(arr1,arr2,axis=1))

[[1 2 3 9]
 [2 6 7 4]]


In [44]:
# Write a Python program to check whether the numpy array is empty or not.


x=eval(input('Enter an array:\n'))
arr1=np.array(x)
arr_size=arr1.size
if arr_size==0:
    print('Empty')
else:
    print('Not empty')


Enter an array:
[]
Empty


In [51]:
# Write a Python program to normalize a 3x3 random matrix.

arr1=np.random.random((3,3))
print('Befor normalization \n',arr1)
a_min,a_max=arr1.min(),arr1.max()
print()
print('After normalization \n',(arr1-a_min)/(a_max-a_min))

Befor normalization 
 [[0.36230734 0.03681539 0.620975  ]
 [0.32932979 0.61288747 0.401199  ]
 [0.71563221 0.9063843  0.37897441]]

After normalization 
 [[0.37431416 0.         0.6717807 ]
 [0.33639013 0.66248008 0.41903937]
 [0.78063603 1.         0.3934812 ]]


In [ ]:
How to ignore all numpy warnings (not recommended)?

In [40]:
# How to swap two rows of an array?

# arr=np.arange(1,13).reshape(2,-1)
# print(arr)
# arr=arr[::-1]
# arr

arr=np.arange(1,13).reshape(2,-1)
print(arr)
arr[[0,1]]=arr[[1,0]]
arr

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


array([[ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [41]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e.,
# resample the elements of an array with replacement N times, compute the mean of
# each sample, and then compute percentiles over the means).

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15122776  0.25918165]


In [47]:
# Python program to create a random vector of size 10 and sort it.

x=np.random.randn(10)
print(x)
x=np.sort(x)
x

[ 0.56871839  0.92243851  1.38955173  0.39279317 -0.18495816 -0.92428905
  1.0163717  -0.30789897  0.6435375  -1.55289537]


array([-1.55289537, -0.92428905, -0.30789897, -0.18495816,  0.39279317,
        0.56871839,  0.6435375 ,  0.92243851,  1.0163717 ,  1.38955173])

In [51]:
# Write a Python program to check two random arrays are equal or not.
arr1=np.random.randn(0,2,10)
arr2=np.random.randn(0,2,10)
arr_equal=np.allclose(arr1,arr2)
print(arr_equal)

True


In [66]:
# Write a Python program to add, subtract,multiply, divide arguments element-wise.

arr1=np.arange(1,13).reshape(4,-1)
print(arr1)
arr2=np.arange(1,13).reshape(4,-1)
print('\n',np.add(arr1,arr2))
print('\n',np.subtract(arr1,arr2))
print('\n',np.multiply(arr1,arr2))
print('\n',np.divide(arr1,arr2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]

 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

 [[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
# Write a Python program to get the dates of yesterday, today and tomorrow.

import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-05-18
Today:  2021-05-19
Tomorrow:  2021-05-20
